### ISSUE TITLE
Stuck on loading screen after hit save

### ISSUE THREAD

**Issue by gndamiao** [nickian/mautic-whitelabeler#145]
I think i've made everything right, but when I change anything at white labeler and click save, the screen get stucked on loading gif screen and dind't save the changes.

I take a look at the log:
[2023-01-13 01:49:43] mautic.CRITICAL: Uncaught PHP Exception Swift_RfcComplianceException: "Address set in PathHeader does not comply with addr-spec of RFC 2822." at /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/PathHeader.php line 150 {"exception":"[object] (Swift_RfcComplianceException(code: 0): Address set in PathHeader does not comply with addr-spec of RFC 2822. at /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/PathHeader.php:150)"} {"hostname":"c2073f1d3273","pid":23429}
[2023-01-13 01:50:08] mautic.NOTICE: PHP Notice - Undefined offset: 1 - in file /var/www/html/app/bundles/EmailBundle/Helper/MailHelper.php - at line 1961 {"idHash":null,"monitoredEmail":false,"settings":{"address":"","host":"imap.zoho.com","port":"993","encryption":"/ssl","user":"gustavo@tropico.me","password":"redacted","use_attachments":"","folder":""},"email":""} {"hostname":"c2073f1d3273","pid":23429}
[2023-01-13 01:50:08] mautic.CRITICAL: Uncaught PHP Exception Swift_RfcComplianceException: "Address set in PathHeader does not comply with addr-spec of RFC 2822." at /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/PathHeader.php line 150 {"exception":"[object] (Swift_RfcComplianceException(code: 0): Address set in PathHeader does not comply with addr-spec of RFC 2822. at /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/PathHeader.php:150)"} {"hostname":"c2073f1d3273","pid":23429}
[2023-01-13 01:59:08] mautic.NOTICE: PHP Notice - Undefined offset: 1 - in file /var/www/html/app/bundles/EmailBundle/Helper/MailHelper.php - at line 1961 {"idHash":null,"monitoredEmail":false,"settings":{"address":"","host":"imap.zoho.com","port":"993","encryption":"/ssl","user":"gustavo@tropico.me","password":"redacted","use_attachments":"","folder":""},"email":""} {"hostname":"c2073f1d3273","pid":23430}
[2023-01-13 01:59:08] mautic.CRITICAL: Uncaught PHP Exception Swift_RfcComplianceException: "Address set in PathHeader does not comply with addr-spec of RFC 2822." at /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/PathHeader.php line 150 {"exception":"[object] (Swift_RfcComplianceException(code: 0): Address set in PathHeader does not comply with addr-spec of RFC 2822. at /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/PathHeader.php:150)"} {"hostname":"c2073f1d3273","pid":23430}

![Captura de Tela 2023-01-13 às 12 58 50](https://user-images.githubusercontent.com/7263682/212363958-3ad31147-77e0-4e4d-9d8d-37d17e924bf9.png)

Does someone has the same issue? Could you help me, please?

Thanks.

**Comment by nickian** [comment]
The messages in the log look like they are from general Mautic errors and warnings, not the whitelabeler. Be careful when you post log messages. You included your email username and password. I edited the comment and redacted the password. 

There's not much I can do without seeing a specific error that is relevant to the whitelabeler.

**Comment by Bamstian** [comment]
> There's not much I can do without seeing a specific error that is relevant to the whitelabeler.

I have the same issue. When i hit "whitelabel" i got the same erros as when i hit save:

<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function imagecreatefrompng() in /var/www/html/mautic-whitelabeler/whitelabeler.php:416
Stack trace:
#0 /var/www/html/mautic-whitelabeler/whitelabeler.php(498): Whitelabeler-&gt;imageResize(250, '/tmp/phpsTac5w', '/var/www/html/m...')
#1 /var/www/html/mautic-whitelabeler/index.php(327): Whitelabeler-&gt;replaceImages('/var/www/html', 'https://m.mento...', '2.16.2', '/tmp/phpsTac5w', '150', Array, '/tmp/phpjuN5Av', '250', Array, '/tmp/phpeHI26t')
#2 {main}
  thrown in <b>/var/www/html/mautic-whitelabeler/whitelabeler.php</b> on line <b>416</b><br />

**Comment by nickian** [comment]
`Call to undefined function imagecreatefrompng()` This is a PHP error. It's not finding the GD library function. Make sure you have installed and enabled the GD extension for your version of PHP.

**Comment by Bamstian** [comment]
> `Call to undefined function imagecreatefrompng()` This is a PHP error. It's not finding the GD library function. Make sure you have installed and enabled the GD extension for your version of PHP. 

Thank you! I am using docker for this project and was on 2.x 🙄

Now I am on 4.10 but get an 403-error even with www-data as owner of the folder, as any other folders in this directory. 

Do you have any tips or best practices for that?

**Comment by nickian** [comment]
Do you have the whitelabeler in the root of the Mautic folder? If so, it's probably the `.htaccess` file preventing access to the directory. If this is the case, you can temporarily rename the `.htaccess` file, run the whitelabeler in the browser, then set the file back to `.htaccess`.

**Comment by Bamstian** [comment]
Yes I do, but I think it has something to with my Docker-Setup. I lost lots of time during my tests and want to test it on a fresh server without docker and with composer-installation of Mautic. Then it may work. I will get back to you here.
